const actionTypes = {
  LOGIN_USER: "LOGIN_USER",
  LOGOUT_USER: "LOGOUT_USER",
  LOAD_USER: "LOAD_USER",
  CLEAR_USER: "CLEAR_USER",
  LOAD_CURRENTPOST: "LOAD_CURRENTPOST",
  LOAD_CATEGORIES: "LOAD_CATEGORIES",
  CREATE_POST: "CREATE_POST",
};

export default actionTypes;
